---
- name: web server installation
  hosts: all
  become: yes
  vars:
    dist_name: "{{ 'centos' if ansible_distribution == 'CentOS'
                   else 'ubuntu' if ansible_distribution == 'Ubuntu'
                   else 'otherlinux' }}"
  tasks: 
    - name: webserver installation
      include_tasks: "{{ dist_name }}.yaml"

    - name: 각 노드별 접속 주소 안내
      debug:
        msg:
          - "{{ ansible_hostname }} => http://{{ ansible_eth0.ipv4.address }}"
