---
- name: web server installation
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: CentOS httpd 설치
      action: "{{ ansible_pkg_mgr }} name=httpd state=present"
      when: ansible_distribution == 'CentOS'

    - name: httpd index.html
      get_url: url=https://www.kbstar.com dest=/var/www/html
      when: ansible_distribution == 'CentOS'

    - name: start httpd
      service: name=httpd state=started enabled=yes
      when: ansible_distribution == 'CentOS'

    - name: stop firewalld
      service: name=firewalld state=stopped enabled=no
      when: ansible_distribution == 'CentOS'

    - name: Ubuntu nginx 설치
      action: "{{ ansible_pkg_mgr }} name=nginx state=latest update_cache=yes"
      when: ansible_distribution == 'Ubuntu'

    - name: nginx index.html
      get_url: url=https://www.kbstar.com dest=/var/www/html/
      when: ansible_distribution == 'Ubuntu'

    - name: stop ufw
      service: name=ufw state=stopped enabled=no
      when: ansible_distribution == 'Ubuntu'

    - name: 각 노드별 접속 주소 안내
      debug:
        msg:
          - "{{ ansible_hostname }} => http://{{ ansible_eth0.ipv4.address }}"
          - "========================="
